image: drecom/ubuntu-ruby:2.3.1

services:
  - mysql:5.6

variables:
  MYSQL_ROOT_PASSWORD: sample_repo
  CAP_USER: "deployer"
  BUNDLE_CACHE: "vendor/bundle/"
  RAILS_ENV: "test"
  CI: "true"

cache:
  untracked: true
  key: "$CI_BUILD_NAME"
  paths:
    - vendor/bundle/

before_script:
  - ./gitlab-ci/setup.sh

test:
  script:
    - bundle exec rake test
  tags:
    # - ruby
    # - mysql
